import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,signOut,updateProfile} from 'firebase/auth';
import {collection,addDoc,getDocs,query,orderBy,limit,serverTimestamp,doc,setDoc,updateDoc} from 'firebase/firestore';
import {ref,uploadBytes,getDownloadURL} from 'firebase/storage';
import {Search,Plus,MapPin,Clock3,PackageSearch,LogOut,CheckCircle2,XCircle,Upload,ShieldCheck} from 'lucide-react';
import {auth,db,storage} from './firebase';
import './styles.css';

const CATEGORIES=['Electronics','Documents','Keys','Wallet','Bag','Clothing','Books','Accessories','Other'];
const emptyForm={type:'lost',title:'',description:'',category:'Electronics',location:'',date:new Date().toISOString().slice(0,10)};

function score(a,b){
 let points=0;const reasons=[];
 if(a.category===b.category){points+=30;reasons.push('same category')}
 const words=s=>new Set(String(s||'').toLowerCase().split(/\W+/).filter(w=>w.length>2));
 const aw=words(a.title+' '+a.description),bw=words(b.title+' '+b.description);
 const overlap=[...aw].filter(x=>bw.has(x));
 if(overlap.length){points+=Math.min(35,overlap.length*10);reasons.push('matching keywords')}
 if(a.location&&b.location&&(a.location.toLowerCase().includes(b.location.toLowerCase())||b.location.toLowerCase().includes(a.location.toLowerCase()))){points+=20;reasons.push('similar location')}
 if(a.date&&b.date){const d=Math.abs(new Date(a.date)-new Date(b.date))/86400000;if(d<=1){points+=15;reasons.push('nearby date')}else if(d<=7){points+=8;reasons.push('close date')}}
 return {value:Math.min(100,points),reasons};
}

function App(){
 const [user,setUser]=useState(null),[view,setView]=useState('home'),[items,setItems]=useState([]),[authMode,setAuthMode]=useState('login'),[authForm,setAuthForm]=useState({name:'',email:'',password:''}),[form,setForm]=useState(emptyForm),[file,setFile]=useState(null),[search,setSearch]=useState(''),[loading,setLoading]=useState(false),[msg,setMsg]=useState('');
 useEffect(()=>onAuthStateChanged(auth,setUser),[]);
 useEffect(()=>{if(user)loadItems()},[user]);
 async function loadItems(){try{const q=query(collection(db,'items'),orderBy('createdAt','desc'),limit(100));const s=await getDocs(q);setItems(s.docs.map(d=>({id:d.id,...d.data()})))}catch(e){console.error(e)}}
 async function authSubmit(e){e.preventDefault();setMsg('');try{if(authMode==='login'){await signInWithEmailAndPassword(auth,authForm.email,authForm.password)}else{const c=await createUserWithEmailAndPassword(auth,authForm.email,authForm.password);await updateProfile(c.user,{displayName:authForm.name});await setDoc(doc(db,'users',c.user.uid),{name:authForm.name,email:authForm.email,createdAt:serverTimestamp()})}}catch(e){setMsg(e.message.replace('Firebase: ','').replace(/ \(auth\/[^)]+\)\.?/,'.'))}}
 async function submitItem(e){e.preventDefault();if(!user)return;setLoading(true);setMsg('');try{let imageUrl='';if(file){const r=ref(storage,`items/${user.uid}/${Date.now()}-${file.name}`);await uploadBytes(r,file);imageUrl=await getDownloadURL(r)}await addDoc(collection(db,'items'),{...form,imageUrl,reporterId:user.uid,reporterName:user.displayName||user.email,status:'open',createdAt:serverTimestamp()});setForm(emptyForm);setFile(null);await loadItems();setView('dashboard');setMsg('Report submitted successfully.')}catch(e){setMsg(e.message)}finally{setLoading(false)}}
 const filtered=useMemo(()=>items.filter(i=>{const s=search.toLowerCase();return !s||[i.title,i.description,i.category,i.location,i.type].join(' ').toLowerCase().includes(s)}),[items,search]);
 if(!user)return <Auth mode={authMode} setMode={setAuthMode} form={authForm} setForm={setAuthForm} submit={authSubmit} msg={msg}/>;
 return <div className="app"><header><div className="brand" onClick={()=>setView('home')}><PackageSearch size={30}/><div><b>SMART LOST & FOUND</b><small>Campus recovery platform</small></div></div><nav><button onClick={()=>setView('home')}>Browse</button><button onClick={()=>setView('report')}>Report</button><button onClick={()=>setView('dashboard')}>Dashboard</button><button className="icon" onClick={()=>signOut(auth)}><LogOut size={18}/></button></nav></header><main>{view==='home'&&<><section className="hero"><div><span className="eyebrow">SAFE • FAST • SMART</span><h1>Find what matters.<br/><em>Return what’s found.</em></h1><p>Report lost or found belongings and let explainable matching connect the right people.</p><div className="search"><Search size={19}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by item, category, location..."/></div></div><div className="hero-card"><ShieldCheck size={38}/><h3>Proof-based recovery</h3><p>Claims are tied to the reported item and can include supporting evidence before handover.</p></div></section><section className="section"><div className="section-head"><div><span className="eyebrow">LIVE LISTINGS</span><h2>Recent reports</h2></div><button className="primary" onClick={()=>setView('report')}><Plus size={18}/> Report item</button></div><div className="grid">{filtered.map(i=><ItemCard key={i.id} item={i}/>)}{!filtered.length&&<Empty/>}</div></section></>}{view==='report'&&<Report form={form} setForm={setForm} file={file} setFile={setFile} submit={submitItem} loading={loading} msg={msg}/>} {view==='dashboard'&&<Dashboard items={items.filter(i=>i.reporterId===user.uid)} allItems={items} reload={loadItems}/>}</main></div>;
}

function Auth({mode,setMode,form,setForm,submit,msg}){return <div className="auth"><div className="auth-box"><PackageSearch size={44}/><span className="eyebrow">CAMPUS RECOVERY</span><h1>SMART LOST & FOUND</h1><p>One place to report, discover and safely recover belongings.</p><form onSubmit={submit}>{mode==='signup'&&<input required placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>}<input required type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input required minLength="6" type="password" placeholder="Password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button className="primary wide">{mode==='login'?'Sign in':'Create account'}</button></form>{msg&&<div className="notice error">{msg}</div>}<button className="link" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Need an account? Create one':'Already have an account? Sign in'}</button></div></div>}

function Report({form,setForm,file,setFile,submit,loading,msg}){return <section className="form-page"><span className="eyebrow">NEW REPORT</span><h1>Tell the campus what happened.</h1><p className="muted">The more accurate the details, the more useful the matching engine becomes.</p><form className="report-form" onSubmit={submit}><div className="seg"><button type="button" className={form.type==='lost'?'active':''} onClick={()=>setForm({...form,type:'lost'})}>I lost something</button><button type="button" className={form.type==='found'?'active':''} onClick={()=>setForm({...form,type:'found'})}>I found something</button></div><label>Item title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Black JBL headphones"/></label><label>Description<textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Colour, markings, model, identifying details..."/></label><div className="two"><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label><label>Date<input type="date" required value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label></div><label>Location<input required value={form.location} onChange={e=>setForm({...form,location:e.target.value})} placeholder="Library, Block A, cafeteria..."/></label><label className="upload"><Upload size={20}/><span>{file?file.name:'Add a photo (optional)'}</span><input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button disabled={loading} className="primary wide">{loading?'Submitting...':'Submit report'}</button>{msg&&<div className="notice">{msg}</div>}</form></section>}

function ItemCard({item}){return <article className="card"><div className="card-img">{item.imageUrl?<img src={item.imageUrl} alt={item.title}/>:<PackageSearch size={38}/>}</div><div className="card-body"><div className="tags"><span className={item.type==='lost'?'lost':'found'}>{item.type.toUpperCase()}</span><span>{item.category}</span></div><h3>{item.title}</h3><p>{item.description}</p><small><MapPin size={14}/>{item.location} · <Clock3 size={14}/>{item.date}</small></div></article>}
function Empty(){return <div className="empty">No reports match your search.</div>}
function Dashboard({items,allItems,reload}){const matches=items.flatMap(i=>allItems.filter(x=>x.type!==i.type&&x.status==='open').map(x=>({a:i,b:x,s:score(i,x)}))).filter(x=>x.s.value>=30).sort((a,b)=>b.s.value-a.s.value);async function status(id,status){await updateDoc(doc(db,'items',id),{status});await reload()}return <section className="section dashboard"><span className="eyebrow">YOUR SPACE</span><h1>Dashboard</h1><div className="stats"><div><b>{items.length}</b><span>Your reports</span></div><div><b>{matches.length}</b><span>Potential matches</span></div></div><h2>Potential matches</h2>{matches.length?<div className="match-list">{matches.slice(0,12).map((m,k)=><div className="match" key={k}><div className="score">{m.s.value}%<small>match</small></div><div><h3>{m.b.title}</h3><p>{m.b.description}</p><small>{m.s.reasons.join(' · ')}</small></div><button onClick={()=>status(m.b.id,'claimed')} className="primary">Claim</button></div>)}</div>:<Empty/>}<h2>Your reports</h2><div className="grid">{items.map(i=><div key={i.id}><ItemCard item={i}/><div className="status-row"><span>Status: <b>{i.status}</b></span>{i.status==='open'&&<button onClick={()=>status(i.id,'resolved')}><CheckCircle2 size={16}/> Mark resolved</button>}{i.status!=='resolved'&&i.status!=='claimed'&&<button onClick={()=>status(i.id,'closed')}><XCircle size={16}/> Close</button>}</div></div>)}</div></section>}

createRoot(document.getElementById('root')).render(<App/>);
